name = "Modern Blog Theme"
description = "A fast, modern, typography-first blog theme with unique card-based layout"
homepage = "https://mattlangford.com"
tags = ["blog", "modern", "typography", "fast", "minimal"]
features = ["responsive", "accessibility", "micro.blog"]
min_version = "0.117.0"

[author]
  name = "Matt Langford"
  homepage = "https://mattlangford.com"